### ISSUE TITLE
pi-zero image differs from pi3 and pi4 images

### ISSUE THREAD

**Issue by robmarkcole** [google-coral/edgetpu-platforms#13]
As title, I've sent an email to support. In summary on pi-zero:
1. SSH is not enabled
2. `all_models` directory is not present

**Comment by mtyka** [comment]
Hi, thanks for pointing that out. Indeed, the pi-zero setup is older, I don't yet have a pi0 version of the 2.11.2 API version, so necessarily the images differ - that's wai. 
However the two specific issues you pointed out can be fixed - i updated the pi0 image accordingly for better consistency with the newer images. Note though that several differences remain, which cannot be reconciled.
