### ISSUE TITLE
Can't install Edge TPU compiler on Dev Board

### ISSUE THREAD

**Issue by scch-sims** [google-coral/edgetpu-platforms#14]
Hello!

I have got a problem with updating my Google Coral Dev Board.
With the command:
`sudo apt-get update`
it won't work. => have a look at my attached file.
Because of this it is not working to install the edgetpu compiler. :/
[Failed_to_Update.txt](https://github.com/google-coral/edgetpu-platforms/files/3493182/Failed_to_Update.txt)

**Comment by mtyka** [comment]
Since this question isn't about this repo (edgetpu-platforms), please email coral-support@google.com who will be able to help.
