### ISSUE TITLE
Can TensorFlow Lite be used for Support Vector Regression presently implemented with 32 bit processor?

### ISSUE THREAD

**Issue by crahim** [google-coral/edgetpu-platforms#17]
We have a sensor program for chemical detection which is presently implemented using Support Vector Regression in a 32 bit processor. Our goal is to miniaturize it into a portable solution. We are considering the use of CORAL platform for that task. Is it possible to implement SVR using Tensor Flow Lite? If not, is there another platform that you can recommend at similar cost?

**Comment by mtyka** [comment]
Tflite/Coral do not support training, so you would not be able to train an SVR.
