### ISSUE TITLE
How to install edgetpu libraries from scratch for a Raspberry pi 4?

### ISSUE THREAD

**Issue by jalbstmeijer** [google-coral/edgetpu-platforms#18]
I want to install the libraries on a docker container on my Raspberry pi 4.
Where do I get this library?

Tried this one, https://github.com/google-coral/edgetpu-platforms/archive/v2.11.1.tar.gz
Which is very confusing, as it only seems to contain something for rpi0 and in the download.sh it still downloads https://github.com/google-coral/edgetpu-platforms/releases/download/v1.9.2/edgetpu_api_1.9.2.tar.gz

**Comment by mtyka** [comment]
We don't offer any from-scratch install scripts for RPI4 yet. Please use the prebuilt Rpi4 image instead. https://github.com/google-coral/edgetpu-platforms/releases/download/v2.11.1/rpi4-raspbian-buster-edgetpu-2.11.1.img.gz
