### ISSUE TITLE
Rpi 4 Buster Image cannot update

### ISSUE THREAD

**Issue by jamesee** [google-coral/edgetpu-platforms#23]
Hi

thanks for the pre-installed Buster rpi 4 image.

I download the image and etch into a 32G sd card.
Started up fine, but when I want to do "sudo apt-get update", it showed the following messages:

Temporary failure resolving 'archive.raspberrypi.org'

I checked my internet connection, it is working fine.

 The ip address kept stuck at 192.168.2.4 no matter how much I tried "sudo dhclient -r" and "sudo dhclient"

I tried etching another SD card with the Buster image from raspberrypi.org, it works fine. IP address cannot be refreshed.

Please look into it.

Regards
James

**Comment by manoj7410** [comment]
@jamesee Are you still facing this issue or can this be closed ?

**Comment by jamesee** [comment]
Please close . Thanks
