### ISSUE TITLE
Proposed change to run_classify.sh

### ISSUE THREAD

**Issue by cloudwiser** [google-coral/edgetpu-platforms#24]
Hi - just a quick note to to say that `run_classify.sh` in `~/simple-demo` should be changed to use the edgetpu version of the mobilenet v2 model i.e. `mobilenet_v2_1.0_224_quant_edgetpu.tflite`

**Comment by manoj7410** [comment]
@cloudwiser Which demo exactly are you referring here ?

**Comment by manoj7410** [comment]
Marking close due to lack of activity. Feel free to reopen if this is still an issue.
