### ISSUE TITLE
img does not start

### ISSUE THREAD

**Issue by heartsomeXPhantom** [google-coral/edgetpu-platforms#25]
I downloaded the image (rpi4-raspbian-buster-edgetpu-2.11.1.img), flashed it to a sd card (32GB, 64 GB), started it on my Rasp Pi 4. Did not boot, terminated with
![2019-11-24 08 26 22](https://user-images.githubusercontent.com/4004550/69491359-4a235680-0e94-11ea-90ea-97dc2a317315.jpg)
 with a kernel panic error.

**Comment by hjonnala** [comment]
@heartsomeXPhantom sorry for delay, are you still facing issue?

**Comment by hjonnala** [comment]
Fell free to reopen if issue still persists.
