### ISSUE TITLE
Provide prebuild image for edgetpu 2.12.2

### ISSUE THREAD

**Issue by thomasdarimont** [google-coral/edgetpu-platforms#26]
It would be great if your team could provide a pre-build image for the edgetpu platform with the edgetpu libraries 2.12.2

See:
https://github.com/google-coral/edgetpu/blob/master/edgetpu/__init__.py

**Comment by cipy** [comment]
@thomasdarimont what's new in 2.12.x? thanks,

**Comment by hjonnala** [comment]
Closing the issue as edgeptu api deprecated. Feel free to reopen if they are any concerns.
