### ISSUE TITLE
no release named edgetpu_api_rpi0_1.9.2.tar.gz

### ISSUE THREAD

**Issue by cipy** [google-coral/edgetpu-platforms#29]
(no comment)

**Comment by hjonnala** [comment]
I believe the correct release name is edgetpu_api_1.9.2.tar.gz. Which can be found here : https://github.com/google-coral/edgetpu-platforms/blob/master/rpi0/download.sh

![Screenshot from 2021-07-12 10-40-22](https://user-images.githubusercontent.com/86132058/125332024-95a2a680-e2fd-11eb-9d90-7cd1ae44820f.png)
