### ISSUE TITLE
SD card Image for Rasberry pi boards

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [google-coral/edgetpu-platforms#7]
Can you please share an SD card image with everything preconfigured for easy and quick evaluation of the device.

**Comment by ShettyHarapanahalli** [comment]
Got the image from the web page - https://github.com/google-coral/edgetpu-platforms/releases

**Comment by mtyka** [comment]
I added a prebuilt image for Raspberry Pi Zero:
https://github.com/google-coral/edgetpu-platforms/releases/download/v1.9.2/rpi0-raspbian-stretch-edgetpu-1.9.2.img.gz
