### ISSUE TITLE
Failed to allocate tensors continued..

### ISSUE THREAD

**Issue by mali30** [google-coral/edgetpu-platforms#8]
The board is not recognized and I keep getting the `failed to allocate tensors` error. I have restarted, shutdown, and also connected and disconnected the usb. No avail. I have also added it to the `plugdev` group by running the command

`sudo usermod -aG plugdev root`

Can someone please give any other suggestion on how I can overcome this issue?

**Comment by mtyka** [comment]
What system/os versions are you using ? Rpi0 or 3 ? What code are you running ?

**Comment by mali30** [comment]
I figured out a quick fix. Ran the get started on the google coral board page and it works after. The problem was it was not detecting the Coral Board. It kept saying Unicorp Chip instead of Google Inc.

**Comment by mtyka** [comment]
Yes, it does say Unicorp Chip. But that's the TPU - great i'm glad you got it working !
